; generated by PrusaSlicer 2.4.2+win64 on 2023-01-19 at 21:43:18 UTC


;
; thumbnail begin 16x16 464
; iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABIUlEQVR4AaWTzUrEMBSF81CCCIO4Ut
; TNbAbtX9o0bdOkhdq1CC7EpfoYuvdn7ZNdPVc6FCtpZRZnkeaerwnnRIRhSGNFUeTV73lRliXFcTxr
; /AskpfwBaK15gQ3AfBpm4GuahgSMVVUxJMsySpLEC0jTlIwx1LYtWWtJDEQAeENF9FSc03N1RJ92n1
; 7NivWQn1Ke52zq+57n4RVj+p1es8mnW5fwdQfPFmDlxax5EGYnABxxKQCzE8C9PNkNkAWbRea3ekUu
; WE8BiOfGRF7zuz2k6+CY494CEAU+IJ6u6+iqTOlRn3GMH3qPI3xRB3xsebnhAqE3SinujMACxrqu+R
; RzTeTrfv8QvqIoSDjnmAra0ipDmEeZBCj/fUhjiV2f8xcqmSr8FxBNXwAAAABJRU5ErkJggg==
; thumbnail end
;

;
; thumbnail begin 220x124 6016
; iVBORw0KGgoAAAANSUhEUgAAANwAAAB8CAYAAAACRt5vAAARZ0lEQVR4Ae2ciXdN1x7H/SPv9Q1V1a
; rSR0dUa3qoqarakHkmiYgYghiySBTvCaHGiCHmUJZnbBdNB1NrXKu0Va0aqig1j+X3znfXiSuSmzuc
; 4bfP/d21vitEcp279/dz9v4N+9SLiooiK9S3b1/KzMykJUuW0Llz5+ju3bt06tQpWrhwIcXHx1OfPn
; 20Fz6j6HHpNIf+NHToUDp58iSZr6NHj1JWVhZZxQhUz8o3w0UnJCTQhAkT6JtvvqELFy7QwYMHFYg6
; DbwAFnkApqSk0Keffkq///47XblyhVavXk2xsbGWwmY5cKaio6MpLS2NiouLady4cVpNgk7G1kG6zD
; s8W1hYSHPnzqW8vDz1PTvYsBw4fx8oNzeXhg8frpZpbgOuk4l1FMf5HjFiBA0bNkx5s7afYw2cvw8I
; 0I4cOUKXL1+mPXv20MiRI1kMush5uT3vcXFxtH37duXFM2fO1LkLYwdcIB8yMTGR5s+frz4gkimTJk
; 1ybcB1MqeX5db8FxQU0OHDh6tyDIjfAvk9FsAFe2dBAmXIkCEUExPj6CDrZMRIlJNegA+x4xo1apTf
; 7aQd0IUFnBUfHqnY8vJylWDBKmj14OpkOpE94GVnZ9OsWbNUUsSKEpUrwFkxEEi7fvLJJyoV+9tvv9
; G2bdvU6mfFwOtkMpE94GH1Ki0tpatXr9Lt27dp3759lpWoHAXOigs2lZOTo0BD7QODgsRKSUmJWvYF
; NFGovkpNTaUDBw7QvXv3VBH70qVLVFRUZKl3HQHOygs2AUlPT6c5c+bQ6dOn6c6dO6pTZf369UHfjX
; QykihwBesBNF4AMLwA3P79+xWAVns3FOiCAs6OCzaFFW306NG0d+9eunbtGt24cUP9GfvuuhIsOplH
; FLrq8hC6nD7++GO1U8ILPpo3b17QiRE7oQsYODsv2BQGBkXx5cuXq5gO/ZjobVu2bFmNqVudzCKyTj
; V5BwVslJvM148//qjCFSd8Gwx0AQHn1EWbECUlJdHEiRPp22+/pZs3b6rtwdatWxWM5oDrZBCR9fK9
; SZeVldH169cVaPDLunXrQs4B2A1dPU6w+QrbSLSCbd68WcV06NzG33UyhchewScZGRm0a9cuVcQ+f/
; 48jR071jXPBgJdPY6w+a522EqiVADYUEbQyRAie+TrD6xwAwYMUPG/HXVcq6GrxxW22oStArabqK+g
; B04gjCwh3Jg2bRpNmTJFFbH7VoOQi4ICjtOFVx9wxHE4a4c9+/Hjx2nq1KnqLqeDWUThaeDAgfTDDz
; +oOA3JNKxq1T3CybsBAcfpgmsadNzVxo8fr4qa33//vWoJQ7yng2FE4QklIjQb40a7dOnSWuedk4f9
; AsfpQv0NPFY085Cr77bC/D5n09Sk9JjeSoNje1JBfFf6b0JHmpvUTml5Smul/6W2qFP4OfP38B4Q3h
; PvrdN4+BPmHEXsun6Ok5dZAxfKJACy6dOnq75M3Pk4ZzN9wTKBqkx/yREBShNGXAPXMYKwes2YMYM2
; bdpE+fn5KnYP5X04eLpG4DhcWKiTA+BWrFhBZ8+eVV0GiPEQ24U6SVYD5gZcwUBoroZuj5UprGBff/
; 01/fHHH6q2tnv3bpWBDPX9OHj7EeA4XFDYxk5PV5nLX375RfVjAj4UQNGP6aRZTMhgYI6ABQqgWysg
; 4rSLFy9W9UEeOnRIbSPDfV8OHlfAcbgQqyYLvXQ4zYtmVWQx0Y/51VdfqSSL3YkVEzIYVifAAoHPiR
; gQc4ft461bt6r6IBcsWGBp2YeD110HzuqJA1g4cLhq1SrVfYB+zBMnTqjnZaKIbgdkOq5kocJn9XxB
; aGzAHJkvZCEHDx5sy/8V0cDZMaCmkpOTafLkyap0gLoNHhhTWVlZ9ZQmK0DTCRgrZdWqh9Vr0aJFVX
; 2QWN02bNigVjs7vRGRwNk5oL4TirsnjmwAOCRUEBOYz7IIBTQkP3SCw05hZQ8VPEC1Y8eOqsQIdiPm
; 07OcUEQB59SgQgALCZWZM2eqrQoK5nhEXzAxnYBmPXjoGAJwP/30E+3cudPy7T5X6DwPnCmsdiiSox
; fPd3XzVyyP9K1jsKorxsM4+97ocCNEFtmtZoWIAM6Nga1JmHiUEXD8B199U88CWuiqLbmCpxxv3LiR
; Zs+erUDj4gNPA8dlkCHEEDhHhdgOp8sBHQrlgC0Sso5OgIexxOqFh/7ieTVIihw7dowGDRrEygueBI
; 7TAEMwArrPKyoqVAyB1rApiZ20MrUOwpjiUChubugAQvzMzQtOQucIcBwH2IQO6h8XJbDZKOwYEENz
; aLVzG7qIBg7CtsdL3SFchTHm3jDtCeA4DzAMoJNpvaBIh85W4DgPrGQh3RNOT3D2hgAnsAl0ApzAJh
; LoBDg/wgTrZMhIENeYTivgOA6gJEgEOg7QRQRwSP3rZECBToDTGjZp1eIv1Om4eccO6DwPnCRJ9BGO
; QHHzD2vguA2WxG36yetbS88CJy1beorj1pIlcNwGSbaS+orTMzKths6TwElWUn9xezy7AOdH8vwR/c
; UtgcIKOE4DI6ubd+TFVc5zwEn7lnfELZYT4GqQFLm9JU7eEuCqSepu3hOnuhwL4LgMBiSlAO/Ja8kT
; TwEn20lvipPHBLgHkuykd8UpWynAPZDEb94Vp5PhAtwDSfzmXXEqDwhwDyTxm3fFKXHiKnBcBkGA87
; Ywt5y8JsAZkqM43hW3IzsCnAAnwAlwApxIgBPgRAKcACfAiQQ4rYCrSHxFKxOJAteK+JdZeU2AM1QW
; 30orE4kCl5QFGAJXEvumViYSBa6p77/KymuuAccJusKYDlqZSBS4hr3bho3PwuXFM8Cl9RTgvKrYnm
; +x8ZkA56MtSc21MpKobm1MbEbRvd9h4zEBzkflMXqZSVS3Snq9wMpjApyPCnpLptJrynv7NVYeE+B8
; lG7EcbKt9I6wneQUv7EAjht02ILoZCpR7ZrQ7XlW3rKCFc8Bl9lDzsV5QVjdEjq1ZOUtAa4WLej9nF
; bmEj2u+X2aU/R7fLKTApwf5XSVvkqdhdUtsX1zdr5iAxxH6Gb1bKSVyUQPhTjci6ubp4HLMmK5dXGS
; QNFNXl7dPA0cNLlHE63MJrA1o/yOjVh6iR1wHKFLfrerkUBprJXpIlkzejzDru5mJWyeBw4a2vlfsr
; XUQFjdkhhuJVkDxxW60d2baWW+SIQtp01Dlt6xmo+IAC7u/V5U3K2hViaMJNgQt8Uwy0oKcGEK8dyU
; rgIdR9g4xm3aAMcZOjQ3C3R8YEOShFv7lp2wRRxwAh0f2KYzh00r4AQ6kcDmMHA6QFfY8SmtzOoF2J
; CNjFTYIho4KMlIpAC6tVKnE9i8AJwO0KFkkNfhWSp7V4702CVsIVNaPsWuIdlp2AQ4H+gGd3qB/tNF
; 4jorpeK17s9Q8hvPaeEDTwCnA3TR0dFKGd1b03jZYlqist7PUU7bh1tIjC93HzjBgiPAcYUuISGBli
; 5dSmvWrKEhQ4ZQTEyMWu1yOzWlyW89TZuTpCUsWJmrWkqL+lXPkxw2bBht27aNli1bRgUFBWqcuXnB
; KQ4cA44bdCkpKbR37166ceMGXbt2jZYsWfKIEfp3e52Gt/knlUpsFzBoJdg+GqDFd2rxyFhPmjSJTp
; 48qcZ6//79lJeXx8oLTjIQscBlZWXRhg0b6MiRI7R27Vq12lX/Gax2AK+gQ30q7SXg+QMtu83TCrSa
; npKcmJhIH3zwAe3evZu+/PJLSktLY+UFzwLnNnSAKjY2Vv0ZMUVSUpJa6er6PYCX9dbLNNYAb14veX
; QDtOEBaANb/o0S2jWv83HkZpxs7iLw57i4OAUjvrrlCaf97zhwbkCHycW2Zs+ePbR+/Xq1uoXyPrEG
; eJmdX6Yx7evT3AgFD6BNM0BLeukvCrSYEBuPU1NTafv27XTo0CH66KOPaMCAAY77wg3vuwKck9BhFc
; PE3rlzh+7evUs///wzDR06NKz3BHjpXV+nwa3/QVO7PUPlUc9rBU0okM03YtmiTg0oETFaGKCZSk5O
; pi+++IKuXr1aFdth22nuQLwIm6vAOQHdyJEj6cyZM2S+jh49aumdNPa9XpRmgIcOilHtjFXvnUa0Jt
; Y7JQW1mnVrSANaPEEJrz1JcR1bWDZ22HVgp4Fk1blz59TN8NSpU7Ry5UrbYzw3Pe8qcHZBh5hg1apV
; 6s6J182bN2n16tUUHx9v2ySa8GHVewhfU+0AW9m3CRUZtcgqyNo2o5i37Tuvhh3IhAkT6PDhw2q+sO
; IhsZKfn29L7c5tv7sOnNXQZWZm0nfffVe1qp09e5ZGjRplm2H8wZdjZO4Gt/67AeCTLAFEhnFldBNV
; NxtplECSjbjszy2jvZBVFxIpgwYNUlnjS5cuqe3/sWPHaN68eSqpYtX/w8Hr9aKiolhcSLiDibvhhx
; 9+qO6QeGHSPvvsM3UHdco4tcPXSgnw5b5uANj2SSP2a0hzDAhXxzR1DK5V0U3VU8wmdm6gbgJpr/yV
; UlrWp0QjJovt2jbsuCzc+UMipaSkRMXZt2/fposXL9LWrVsVjOG+PwePgzU2wIUDHe6QFRUV6u5479
; 49unz5MhUXF7NsJwKACb26UFqXVpTVvomqXw0yIITyDRBxeqH4AYyzezaixe83VlBWV0U1LXqvsdJC
; QzPfflZ1yow1sqlQ/1efoLRWTynhyVhot+L6WAOEA8OHD1fbStw8r1+/Tps3bw4rruPi7yrgdIcOYC
; 1evFjFAbt27aJ+/fq5ZphwQUzu0Z5SDRj7dXyJMto1MfS8UtabDf7UGw0o26h9ZRpfoYzWD5XetjGl
; /vtFSu3wIiV1bkkJ3dtR3DtdKK5nF63GQvW1ZmSoLeWBAwdUS1ioW0suvjY5qwJON+iQPsbd0FzF8B
; VFbI59eqLQZBbKfYvl1efdn7j42ZexR4DTBbqBAweqNqEdO3ao1L8Oneii8IUGc9TusIspLS31u+px
; 8XF1vh4DjhN0NYGHABpZyFu3bqmgetq0aQJchCg3N1eFDWg2P3HiRI3ZZ07erYmtGoHjDB22jRs3bl
; R3unHjxmlhFJE1wtYSqxxqqjhW1b9//0f+nZNna+OKPXAmZL7d/GYjrA4mEdkr+ADeSE9PV2UFfI+D
; b4MGjgN0GMgtW7bQ8ePHaefOnaoVyIRQJIIXABrKBmgLQymhsLBQrYRu+tYfU36BcxM6HFI8ffp0Vc
; fIvn371B1MgBOZMm/KKAmhowj9mDjoijKC6RVOsAUEnNPQIe2L/TkKnmYf5Lp161QquPrP6mQOkXWq
; 7gF0E02cOFEdJoZfrly5Qp9//jmNGDHisZ93E7aAgXMKOgTByELdv39fwXb+/HkaM2aM39/RySii8F
; WbD8x+zE2bNqlOI7T24XTI7Nmz1SrIAbaggLMTOgwk0vu4M+GFrQH247hzBfMeIu8qUA9gKzl9+nRV
; NkA/5oULF1SMh9qtXf4NhqGggLMDOhQvsfwDMrwAHeALdJAFPG8rFA8gLMF2Eok29GOiZouT5TgGhK
; ymlf4Nlp+ggbMSOsCGQcE5KACHPTh66Kx4b51MJbIGtOrzDy8tXLiQfv31VxXbIfGG41tW+TcUdkIC
; zirwsLdGgyqO0WBgcGeyajAEPD1l9fzDY6NHj1bbyrKyMkviuXCYCQu4UKBDERsy/24Wsa0eaAFPL9
; k9/76C31C/y87ODhrAcHkJG7hAocOgzpw5Ux0uRCbS7INzcqAFPH5yev4h1HgPHjyoiuXIauI5N07A
; ZhlwgUCHR1zj2DziNTzYB4+/dmOwBTwecnPusbrhSW44sIyCOZ4WVtcuyypOLAOuLvBwKBQ1ERS1fb
; eUHKSTUXUWp/nGCfKioiL1WA4k76qDZTVotgFnXiw6Q7CK5eTksBpsAc95cZ5zX7gQz+F8JU4kYMWz
; gw1bgMMFo/CIij8OiZpNxzpJJ0NzlE5zDaFTpbKyUj0jE6FPeXm5elit1Wz8HwbkMfnmRMndAAAAAE
; lFTkSuQmCC
; thumbnail end
;
; 

; external perimeters extrusion width = 6.00mm
; perimeters extrusion width = 6.00mm
; infill extrusion width = 6.00mm
; solid infill extrusion width = 6.00mm
; top infill extrusion width = 6.00mm
; first layer extrusion width = 6.00mm

M73 P0 R28
M107
;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S170 ; set extruder temp for bed leveling
M140 S100 ; set bed temp
M109 R170 ; wait for bed leveling temp
M190 S100 ; wait for bed temp
G28 ; home all without mesh bed level
G29 ; mesh bed leveling 
M104 S215 ; set extruder temp
G92 E0.0
G1 Y-2.0 X179 F2400
G1 Z3 F720
M109 S215 ; wait for extruder temp

; intro line
G1 X170 F1000
G1 Z0.2 F720
G1 X110.0 E8.0 F900
G1 X40.0 E10.0 F700
G92 E0.0

M221 S95 ; set flow
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.2 ; Filament gcode LA 1.5
; ; Filament gcode LA 1.0
M107
;LAYER_CHANGE
;Z:0.075
;HEIGHT:0.075
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.075


M73 P0 R27
G1 Z.075 F9000
;AFTER_LAYER_CHANGE
;0.075
G1 X79.193 Y78.912
M204 S800
;TYPE:Skirt/Brim
;WIDTH:6
G1 F13.369
G1 X80.364 Y77.88 E.32746
G1 X81.632 Y76.972 E.3274
M73 P1 R27
G1 X82.985 Y76.196 E.32745
G1 X84.161 Y75.66 E.27124
M73 P2 R27
G1 X85.633 Y75.145 E.32741
G1 X87.151 Y74.781 E.32752
G1 X88.697 Y74.572 E.32739
M73 P3 R27
G1 X90.208 Y74.518 E.31747
G1 X91.561 Y74.596 E.2845
M73 P4 R26
G1 X93.104 Y74.831 E.32746
G1 X94.614 Y75.22 E.32742
G1 X96.078 Y75.76 E.32743
M73 P5 R26
G1 X97.244 Y76.316 E.27121
G1 X98.584 Y77.115 E.32742
M73 P6 R26
G1 X99.838 Y78.044 E.32747
G1 X100.991 Y79.095 E.32747
G1 X102.032 Y80.256 E.32739
M73 P7 R26
G1 X102.812 Y81.307 E.27467
M73 P7 R25
G1 X103.622 Y82.64 E.32742
M73 P8 R25
G1 X104.293 Y84.049 E.32746
G1 X104.82 Y85.517 E.32737
G1 X105.196 Y87.031 E.32753
M73 P9 R25
G1 X105.417 Y88.575 E.32734
G1 X105.482 Y90.134 E.32744
M73 P10 R25
G1 X105.39 Y91.691 E.32741
G1 X105.142 Y93.232 E.3275
M73 P11 R25
G1 X104.82 Y94.483 E.27124
M73 P11 R24
G1 X104.293 Y95.951 E.32738
G1 X103.622 Y97.36 E.32746
M73 P12 R24
G1 X102.812 Y98.693 E.32743
G1 X101.872 Y99.938 E.32749
M73 P13 R24
G1 X100.812 Y101.083 E.32739
G1 X99.642 Y102.114 E.32747
G1 X98.374 Y103.023 E.32747
M73 P14 R24
G1 X97.021 Y103.8 E.32741
M73 P14 R23
G1 X95.64 Y104.419 E.31751
M73 P15 R23
G1 X94.358 Y104.857 E.2845
G1 X92.841 Y105.22 E.32741
G1 X91.295 Y105.429 E.32746
M73 P16 R23
G1 X89.735 Y105.481 E.32743
G1 X88.446 Y105.405 E.27119
M73 P17 R23
G1 X86.903 Y105.171 E.32744
G1 X85.392 Y104.782 E.32747
G1 X83.928 Y104.243 E.32743
M73 P18 R22
G1 X82.526 Y103.56 E.32743
G1 X81.407 Y102.881 E.27463
M73 P19 R22
G1 X80.155 Y101.951 E.32744
G1 X79.002 Y100.899 E.32743
G1 X77.961 Y99.737 E.32741
M73 P20 R22
G1 X77.043 Y98.477 E.32741
G1 X76.381 Y97.367 E.27123
M73 P21 R22
G1 X75.709 Y95.959 E.32746
G1 X75.182 Y94.491 E.32745
M73 P21 R21
G1 X74.805 Y92.977 E.32745
M73 P22 R21
G1 X74.583 Y91.433 E.32743
G1 X74.517 Y89.874 E.32741
M73 P23 R21
G1 X74.608 Y88.317 E.3274
G1 X74.855 Y86.776 E.32746
G1 X75.257 Y85.269 E.32745
M73 P24 R21
G1 X75.789 Y83.853 E.31755
G1 X76.381 Y82.633 E.28449
M73 P25 R21
G1 X77.191 Y81.3 E.32745
M73 P25 R20
G1 X78.132 Y80.056 E.32741
M73 P26 R20
G1 X78.581 Y79.572 E.13857
M204 S1250
; printing object helper_disk.stl id:0 copy 0
G1 X86.69 Y86.964 F9000
M204 S800
;TYPE:External perimeter
G1 F13.369
G1 X86.834 Y86.807 E.04459
G1 X87.171 Y86.505 E.09508
G1 X87.537 Y86.238 E.09508
G1 X87.928 Y86.009 E.09509
G1 X88.34 Y85.821 E.09508
M73 P27 R20
G1 X88.769 Y85.675 E.09508
G1 X89.21 Y85.574 E.09509
G1 X89.663 Y85.516 E.09579
G1 X90.101 Y85.504 E.09183
G1 X90.396 Y85.52 E.06204
G1 X90.863 Y85.587 E.09902
G1 X91.302 Y85.697 E.09508
G1 X91.729 Y85.85 E.09509
G1 X92.138 Y86.045 E.09508
M73 P28 R20
G1 X92.525 Y86.28 E.09509
G1 X92.886 Y86.553 E.09508
G1 X93.219 Y86.861 E.09509
G1 X93.535 Y87.22 E.10038
G1 X93.685 Y87.422 E.05283
G1 X93.937 Y87.829 E.10039
G1 X94.135 Y88.236 E.09508
G1 X94.292 Y88.661 E.09509
M73 P28 R19
G1 X94.405 Y89.1 E.09509
M73 P29 R19
G1 X94.473 Y89.548 E.09508
G1 X94.496 Y90 E.09509
G1 X94.473 Y90.452 E.09509
G1 X94.405 Y90.9 E.09508
G1 X94.292 Y91.339 E.09509
G1 X94.135 Y91.764 E.09509
G1 X93.937 Y92.171 E.09508
G1 X93.698 Y92.557 E.09509
M73 P30 R19
G1 X93.422 Y92.916 E.09509
G1 X93.111 Y93.245 E.09508
G1 X92.769 Y93.542 E.09508
G1 X92.398 Y93.803 E.09509
G1 X92.004 Y94.025 E.09508
G1 X91.588 Y94.206 E.09509
G1 X91.157 Y94.345 E.09509
G1 X90.714 Y94.439 E.09508
M73 P31 R19
G1 X90.239 Y94.491 E.10038
G1 X89.987 Y94.498 E.05285
G1 X89.509 Y94.469 E.10038
G1 X89.062 Y94.397 E.09509
G1 X88.624 Y94.281 E.09508
G1 X88.201 Y94.121 E.09508
G1 X87.773 Y93.907 E.10039
G1 X87.557 Y93.777 E.05284
G1 X87.171 Y93.495 E.10038
M73 P32 R19
G1 X86.834 Y93.193 E.09508
G1 X86.528 Y92.858 E.09509
G1 X86.258 Y92.494 E.09508
G1 X86.026 Y92.105 E.09509
M73 P32 R18
G1 X85.835 Y91.694 E.09508
G1 X85.685 Y91.267 E.09509
G1 X85.58 Y90.826 E.09508
G1 X85.519 Y90.377 E.09509
M73 P33 R18
G1 X85.504 Y89.924 E.09508
G1 X85.534 Y89.472 E.09508
G1 X85.61 Y89.026 E.09508
G1 X85.731 Y88.586 E.09579
G1 X85.888 Y88.177 E.09183
G1 X86.153 Y87.683 E.11763
M204 S1250
; stop printing object helper_disk.stl id:0 copy 0
M106 S84.15
;LAYER_CHANGE
;Z:0.15
;HEIGHT:0.075
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.15


G1 Z.15 F9000
;AFTER_LAYER_CHANGE
;0.15
M140 S60 ; set bed temperature
G1 X76.776 Y81.983
;TYPE:Skirt/Brim
G1 F13.369
G1 X77.191 Y81.3 E.16767
G1 X78.132 Y80.056 E.32741
M73 P34 R18
G1 X79.193 Y78.912 E.32747
G1 X80.364 Y77.88 E.32746
G1 X81.632 Y76.972 E.3274
M73 P35 R18
G1 X82.985 Y76.196 E.32745
G1 X84.161 Y75.66 E.27124
M73 P36 R17
G1 X85.633 Y75.145 E.32741
G1 X87.151 Y74.781 E.32752
G1 X88.697 Y74.572 E.32739
M73 P37 R17
G1 X90.208 Y74.518 E.31747
G1 X91.561 Y74.596 E.2845
M73 P38 R17
G1 X93.104 Y74.831 E.32746
G1 X94.614 Y75.22 E.32742
G1 X96.078 Y75.76 E.32743
M73 P39 R17
G1 X97.244 Y76.316 E.27121
M73 P39 R16
G1 X98.584 Y77.115 E.32742
M73 P40 R16
G1 X99.838 Y78.044 E.32747
G1 X100.991 Y79.095 E.32747
G1 X102.032 Y80.256 E.32739
M73 P41 R16
G1 X102.812 Y81.307 E.27467
G1 X103.622 Y82.64 E.32742
M73 P42 R16
G1 X104.293 Y84.049 E.32746
G1 X104.82 Y85.517 E.32737
G1 X105.196 Y87.031 E.32753
M73 P43 R15
G1 X105.417 Y88.575 E.32734
G1 X105.482 Y90.134 E.32744
M73 P44 R15
G1 X105.39 Y91.691 E.32741
G1 X105.142 Y93.232 E.3275
M73 P45 R15
G1 X104.82 Y94.483 E.27124
G1 X104.293 Y95.951 E.32738
G1 X103.622 Y97.36 E.32746
M73 P46 R15
G1 X102.812 Y98.693 E.32743
G1 X101.872 Y99.938 E.32749
M73 P47 R14
G1 X100.812 Y101.083 E.32739
G1 X99.642 Y102.114 E.32747
G1 X98.374 Y103.023 E.32747
M73 P48 R14
G1 X97.021 Y103.8 E.32741
G1 X95.64 Y104.419 E.31751
M73 P49 R14
G1 X94.358 Y104.857 E.2845
G1 X92.841 Y105.22 E.32741
G1 X91.295 Y105.429 E.32746
M73 P50 R13
G1 X89.735 Y105.481 E.32743
G1 X88.446 Y105.405 E.27119
M73 P51 R13
G1 X86.903 Y105.171 E.32744
G1 X85.392 Y104.782 E.32747
G1 X83.928 Y104.243 E.32743
M73 P52 R13
G1 X82.526 Y103.56 E.32743
G1 X81.407 Y102.881 E.27463
M73 P53 R13
G1 X80.155 Y101.951 E.32744
G1 X79.002 Y100.899 E.32743
M73 P53 R12
G1 X77.961 Y99.737 E.32741
M73 P54 R12
G1 X77.043 Y98.477 E.32741
G1 X76.381 Y97.367 E.27123
M73 P55 R12
G1 X75.709 Y95.959 E.32746
G1 X75.182 Y94.491 E.32745
G1 X74.805 Y92.977 E.32745
M73 P56 R12
G1 X74.583 Y91.433 E.32743
G1 X74.517 Y89.874 E.32741
M73 P57 R12
G1 X74.608 Y88.317 E.3274
M73 P57 R11
G1 X74.855 Y86.776 E.32746
G1 X75.257 Y85.269 E.32745
M73 P58 R11
G1 X75.789 Y83.853 E.31755
G1 X76.32 Y82.758 E.25537
; printing object helper_disk.stl id:0 copy 0
M73 P59 R11
G1 X86.111 Y87.74 F9000
M204 S800
;TYPE:External perimeter
G1 F13.369
G1 X86.243 Y87.526 E.05284
G1 X86.528 Y87.142 E.10038
G1 X86.834 Y86.807 E.09509
G1 X87.171 Y86.505 E.09508
G1 X87.537 Y86.238 E.09508
G1 X87.928 Y86.009 E.09509
M73 P60 R11
G1 X88.34 Y85.821 E.09508
G1 X88.769 Y85.675 E.09508
G1 X89.21 Y85.574 E.09508
G1 X89.671 Y85.515 E.09754
G1 X90.025 Y85.504 E.07414
G1 X90.406 Y85.522 E.08012
G1 X90.863 Y85.587 E.09689
G1 X91.302 Y85.697 E.09508
M73 P61 R10
G1 X91.729 Y85.85 E.09509
G1 X92.138 Y86.045 E.09508
G1 X92.525 Y86.28 E.09508
G1 X92.886 Y86.553 E.09508
G1 X93.219 Y86.861 E.09509
G1 X93.535 Y87.22 E.10038
G1 X93.685 Y87.422 E.05283
G1 X93.937 Y87.829 E.10039
G1 X94.135 Y88.236 E.09508
M73 P62 R10
G1 X94.292 Y88.661 E.09508
G1 X94.405 Y89.1 E.09509
G1 X94.473 Y89.548 E.09508
G1 X94.496 Y90 E.09508
G1 X94.473 Y90.452 E.09509
G1 X94.405 Y90.9 E.09508
G1 X94.292 Y91.339 E.09509
G1 X94.135 Y91.764 E.09509
M73 P63 R10
G1 X93.937 Y92.171 E.09508
G1 X93.698 Y92.557 E.09509
G1 X93.422 Y92.916 E.09508
G1 X93.111 Y93.245 E.09509
G1 X92.769 Y93.542 E.09508
G1 X92.398 Y93.803 E.09509
G1 X92.004 Y94.025 E.09508
G1 X91.588 Y94.206 E.09508
G1 X91.157 Y94.345 E.09509
M73 P64 R10
G1 X90.714 Y94.439 E.09508
G1 X90.239 Y94.491 E.10038
G1 X89.987 Y94.498 E.05285
M73 P64 R9
G1 X89.509 Y94.469 E.10038
G1 X89.062 Y94.397 E.09508
G1 X88.624 Y94.281 E.09509
G1 X88.201 Y94.121 E.09509
G1 X87.773 Y93.907 E.10038
M73 P65 R9
G1 X87.557 Y93.777 E.05285
G1 X87.171 Y93.495 E.10038
G1 X86.834 Y93.193 E.09508
G1 X86.528 Y92.858 E.09509
G1 X86.258 Y92.494 E.09508
G1 X86.026 Y92.105 E.09509
G1 X85.835 Y91.694 E.09508
G1 X85.685 Y91.267 E.09509
G1 X85.58 Y90.826 E.09508
M73 P66 R9
G1 X85.519 Y90.377 E.09508
G1 X85.504 Y89.924 E.09508
G1 X85.534 Y89.472 E.09508
G1 X85.61 Y89.026 E.09508
G1 X85.742 Y88.56 E.10162
M204 S1250
; stop printing object helper_disk.stl id:0 copy 0
M106 S170.85
;LAYER_CHANGE
;Z:0.225
;HEIGHT:0.075
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.225


G1 Z.225 F9000
;AFTER_LAYER_CHANGE
;0.225
G1 X75.471 Y84.699
;TYPE:Skirt/Brim
G1 F13.369
G1 X75.789 Y83.853 E.18968
G1 X76.381 Y82.633 E.28449
M73 P67 R9
G1 X77.191 Y81.3 E.32745
G1 X78.132 Y80.056 E.32741
G1 X79.193 Y78.912 E.32747
M73 P68 R8
G1 X80.364 Y77.88 E.32746
G1 X81.632 Y76.972 E.3274
M73 P69 R8
G1 X82.985 Y76.196 E.32745
G1 X84.161 Y75.66 E.27124
G1 X85.633 Y75.145 E.32741
M73 P70 R8
G1 X87.151 Y74.781 E.32752
G1 X88.697 Y74.572 E.32739
M73 P71 R8
G1 X90.208 Y74.518 E.31747
G1 X91.561 Y74.596 E.2845
M73 P71 R7
G1 X93.104 Y74.831 E.32746
M73 P72 R7
G1 X94.614 Y75.22 E.32742
G1 X96.078 Y75.76 E.32743
M73 P73 R7
G1 X97.244 Y76.316 E.27121
G1 X98.584 Y77.115 E.32742
G1 X99.838 Y78.044 E.32747
M73 P74 R7
G1 X100.991 Y79.095 E.32747
G1 X102.032 Y80.256 E.32739
M73 P75 R7
G1 X102.812 Y81.307 E.27467
M73 P75 R6
G1 X103.622 Y82.64 E.32742
G1 X104.293 Y84.049 E.32746
M73 P76 R6
G1 X104.82 Y85.517 E.32737
G1 X105.196 Y87.031 E.32753
M73 P77 R6
G1 X105.417 Y88.575 E.32734
G1 X105.482 Y90.134 E.32744
G1 X105.39 Y91.691 E.32741
M73 P78 R6
G1 X105.142 Y93.232 E.3275
M73 P78 R5
G1 X104.82 Y94.483 E.27124
M73 P79 R5
G1 X104.293 Y95.951 E.32738
G1 X103.622 Y97.36 E.32746
G1 X102.812 Y98.693 E.32743
M73 P80 R5
G1 X101.872 Y99.938 E.32749
G1 X100.812 Y101.083 E.32739
M73 P81 R5
G1 X99.642 Y102.114 E.32747
G1 X98.374 Y103.023 E.32747
M73 P82 R5
G1 X97.021 Y103.8 E.32741
M73 P82 R4
G1 X95.64 Y104.419 E.31751
G1 X94.358 Y104.857 E.2845
M73 P83 R4
G1 X92.841 Y105.22 E.32741
G1 X91.295 Y105.429 E.32746
M73 P84 R4
G1 X89.735 Y105.481 E.32743
G1 X88.446 Y105.405 E.27119
G1 X86.903 Y105.171 E.32744
M73 P85 R4
G1 X85.392 Y104.782 E.32747
G1 X83.928 Y104.243 E.32743
M73 P86 R3
G1 X82.526 Y103.56 E.32743
G1 X81.407 Y102.881 E.27463
G1 X80.155 Y101.951 E.32744
M73 P87 R3
G1 X79.002 Y100.899 E.32743
G1 X77.961 Y99.737 E.32741
M73 P88 R3
G1 X77.043 Y98.477 E.32741
G1 X76.381 Y97.367 E.27123
G1 X75.709 Y95.959 E.32746
M73 P89 R3
G1 X75.182 Y94.491 E.32745
M73 P89 R2
G1 X74.805 Y92.977 E.32745
M73 P90 R2
G1 X74.583 Y91.433 E.32743
G1 X74.517 Y89.874 E.32741
G1 X74.608 Y88.317 E.3274
M73 P91 R2
G1 X74.855 Y86.776 E.32746
G1 X75.182 Y85.55 E.26643
; printing object helper_disk.stl id:0 copy 0
M73 P92 R2
G1 X85.737 Y88.565 F9000
M204 S800
;TYPE:External perimeter
G1 F13.369
G1 X85.824 Y88.328 E.05284
G1 X86.026 Y87.895 E.10038
G1 X86.258 Y87.506 E.09508
G1 X86.528 Y87.142 E.09509
G1 X86.834 Y86.807 E.09509
G1 X87.171 Y86.505 E.09508
M73 P93 R1
G1 X87.537 Y86.238 E.09508
G1 X87.928 Y86.009 E.09508
G1 X88.34 Y85.821 E.09509
G1 X88.769 Y85.675 E.09508
G1 X89.21 Y85.574 E.09508
G1 X89.683 Y85.514 E.09991
G1 X89.949 Y85.503 E.05591
G1 X90.413 Y85.523 E.09757
G1 X90.863 Y85.587 E.09531
M73 P94 R1
G1 X91.302 Y85.697 E.09509
G1 X91.729 Y85.85 E.09509
G1 X92.138 Y86.045 E.09508
G1 X92.525 Y86.28 E.09508
G1 X92.886 Y86.553 E.09509
G1 X93.219 Y86.861 E.09508
G1 X93.535 Y87.22 E.10038
G1 X93.685 Y87.422 E.05283
M73 P95 R1
G1 X93.937 Y87.829 E.10039
G1 X94.135 Y88.236 E.09508
G1 X94.292 Y88.661 E.09509
G1 X94.405 Y89.1 E.09508
G1 X94.473 Y89.548 E.09509
G1 X94.496 Y90 E.09508
G1 X94.473 Y90.452 E.09509
G1 X94.405 Y90.9 E.09508
G1 X94.292 Y91.339 E.09508
M73 P96 R1
G1 X94.135 Y91.764 E.09509
G1 X93.937 Y92.171 E.09508
G1 X93.698 Y92.557 E.09509
G1 X93.422 Y92.916 E.09508
M73 P96 R0
G1 X93.111 Y93.245 E.09508
G1 X92.769 Y93.542 E.09508
G1 X92.398 Y93.803 E.09508
G1 X92.004 Y94.025 E.09509
M73 P97 R0
G1 X91.588 Y94.206 E.09509
G1 X91.157 Y94.345 E.09508
G1 X90.714 Y94.439 E.09508
G1 X90.239 Y94.491 E.10038
G1 X89.987 Y94.498 E.05285
G1 X89.509 Y94.469 E.10038
G1 X89.062 Y94.397 E.09508
G1 X88.624 Y94.281 E.09509
G1 X88.201 Y94.121 E.09508
M73 P98 R0
G1 X87.773 Y93.907 E.10039
G1 X87.557 Y93.777 E.05284
G1 X87.171 Y93.495 E.10039
G1 X86.834 Y93.193 E.09508
G1 X86.528 Y92.858 E.09509
G1 X86.258 Y92.494 E.09508
G1 X86.026 Y92.105 E.09509
G1 X85.835 Y91.694 E.09509
M73 P99 R0
G1 X85.685 Y91.267 E.09508
G1 X85.58 Y90.826 E.09508
G1 X85.519 Y90.377 E.09509
G1 X85.504 Y89.924 E.09508
G1 X85.54 Y89.442 E.10162
M204 S1250
; stop printing object helper_disk.stl id:0 copy 0
M107
;TYPE:Custom
; Filament-specific end gcode
G1 E-1 F2100 ; retract
G1 Z2.225 F720 ; Move print head up
G1 X178 Y178 F4200 ; park print head
G1 Z30.225 F720 ; Move print head further up
G4 ; wait
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M221 S100 ; reset flow
M900 K0 ; reset LA
M84 ; disable motors
M73 P100 R0
; filament used [mm] = 77.88
; filament used [cm3] = 0.17
; filament used [g] = 0.45
; filament cost = 0.00
; total filament used [g] = 0.45
; total filament cost = 0.00
; estimated printing time (normal mode) = 28m 6s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,180x0,180x180,0x180
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 5
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.85
; bridge_speed = 5
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.4";"nozzle_diameter[0]!=0.8 and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1250
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MINI
; deretract_speed = 40
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G1 E-1 F2100 ; retract\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)}{endif} F720 ; Move print head up\nG1 X178 Y178 F4200 ; park print head\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+30, max_print_height)}{endif} F720 ; Move print head further up\nG4 ; wait\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM221 S100 ; reset flow\nM900 K0 ; reset LA\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 6
; external_perimeter_speed = 5
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 35
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 6
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 2.62
; filament_density = 2.7
; filament_diameter = 1.65
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0.1
; filament_minimal_purge_on_wipe_tower = 2
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_layer_change = 0
; filament_settings_id = rotoforgealuminum1100
; filament_soluble = 0
; filament_spool_weight = 201
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Prusa Polymers
; fill_angle = 45
; fill_density = 0%
; fill_pattern = gyroid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 100
; first_layer_extrusion_width = 6
; first_layer_height = 0.075
; first_layer_speed = 5
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 5
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 6
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 5
; inherits_cummulative = "0.15mm QUALITY @MINI";"Prusament PLA";"Original Prusa MINI & MINI+"
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.075
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 1250
; machine_max_acceleration_retracting = 1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1250
; machine_max_acceleration_y = 1250
; machine_max_acceleration_z = 400
; machine_max_feedrate_e = 80
; machine_max_feedrate_x = 180
; machine_max_feedrate_y = 180
; machine_max_feedrate_z = 12
; machine_max_jerk_e = 10
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 2
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.1
; max_print_height = 180
; max_print_speed = 10
; max_volumetric_speed = 0
; min_fan_speed = 100
; min_layer_height = 0.05
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 6
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; overhangs = 0
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 6
; perimeter_speed = 5
; perimeters = 1
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.075mmrotoforgetestcircle
; printer_model = MINI
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MINI\n
; printer_settings_id = rotoforgetestcircle
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1.5
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 0
; retract_length_toolchange = 4
; retract_lift = 0.2
; retract_lift_above = 0
; retract_lift_below = 179
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 70
; seam_position = nearest
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 15
; small_perimeter_speed = 5
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 6
; solid_infill_speed = 5
; spiral_vase = 1
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S170 ; set extruder temp for bed leveling\nM140 S[first_layer_bed_temperature] ; set bed temp\nM109 R170 ; wait for bed leveling temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nG28 ; home all without mesh bed level\nG29 ; mesh bed leveling \nM104 S[first_layer_temperature] ; set extruder temp\nG92 E0.0\nG1 Y-2.0 X179 F2400\nG1 Z3 F720\nM109 S[first_layer_temperature] ; wait for extruder temp\n\n; intro line\nG1 X170 F1000\nG1 Z0.2 F720\nG1 X110.0 E8.0 F900\nG1 X40.0 E10.0 F700\nG92 E0.0\n\nM221 S95 ; set flow
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 5
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; temperature = 215
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 0
; threads = 4
; thumbnails = 16x16,220x124
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 6
; top_solid_infill_speed = 5
; top_solid_layers = 0
; top_solid_min_thickness = 0.7
; travel_speed = 150
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
